### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by rocpengliu** [thclark/cpplot#17]
HI, 

I got an error;
CMake Error: The source directory "/home/peng/cpplot/build" does not exist.
when using;
cmake . -B build

Any idea about this?
Thank you so much!

**Comment by thclark** [comment]
What directory are you running this from (it should be `home/peng/cpplot`)?
Have you tried running `mkdir build` before this?
What version of cpplot are you using?

**Comment by rocpengliu** [comment]
I have followed the info 

git clone https://github.com/thclark/cpplot
cd cpplot && cmake . -B build

and got the error

**Comment by thclark** [comment]
Can you answer the questions above, please? It helps OSS maintainers support you if you give clear answers to questions, rather than repeating the original issue.

I suspect that cmake isn't making the build directory for you. Try:
```
cd /home/peng/cpplot
mkdir build
cmake . -B build
```

**Comment by rocpengliu** [comment]
OH, Sorry for the late response.
This problem has been solved. But got another error. I suspect it caused by dependencies.
Thank you.
