### ISSUE TITLE
Can it read Csv file and plot graph of that data

### ISSUE THREAD

**Issue by ritesh-ojha** [thclark/cpplot#25]

**Comment by ritesh-ojha** [comment]
I want to about. It take user input regarding file like csv txt . or not. if it take then it plot graph or not.

**Comment by thclark** [comment]
Hi @ritesh-ojha welcome to cpplot.

No, this library isn't intended for reading files like CSV or TXT, that's out of scope for the library (there are many CSV reading libraries available, it doesn't make sense to duplicate the effort).

It does however permit to you plot the data once you've read it in.
